/*
 * Copyright (C) 2019 Tristan Muller
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package github.karakoukie.jumlcreator.views;

import github.karakoukie.jumlcreator.classes.methods.JMethod;
import github.karakoukie.jumlcreator.data.JDataType;
import github.karakoukie.jumlcreator.nodes.JAccessKeyword;
import github.karakoukie.jumlcreator.nodes.JImplementationKeyword;
import java.util.function.Consumer;
import org.apache.http.annotation.GuardedBy;

/**
 *
 * @author Tristan Muller
 */
public class AddMethodDialog extends java.awt.Dialog {

    private final ElementListPanel fieldsPanel;
    
    @GuardedBy("this")
    private Runnable onAcceptCallback;
    
    @GuardedBy("this")
    private Consumer<String> onChangeNameCallback;
    
    private boolean validName;
    
    /**
     * Creates new form CreateProjectDialog
     * @param parent
     */
    public AddMethodDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        this.onAcceptCallback = null;
        this.onChangeNameCallback = null;
        setLocationRelativeTo(parent);
        jPanelError.setVisible(false);
        this.fieldsPanel = new ElementListPanel();
        this.fieldsPanel.setType(ElementListPanel.FIELD_TYPE);
        jPanelFields.add(fieldsPanel);
    }
    
    public final JMethod getMethod() {
        final JMethod method = new JMethod();
        
        method.setName(jTextFieldName.getText());
        method.setDescription(jTextAreaDesc.getText());
        method.setAccessKeyword(JAccessKeyword.valueOf(
                (String) jComboBoxAccessibility.getSelectedItem()));
        method.setImplementationKeyword(JImplementationKeyword.valueOf(
                (String) jComboBoxKeyword.getSelectedItem()));
        
        method.getReturnType().setDataType(JDataType.getFromName(
                (String) jComboBoxReturn.getSelectedItem()));
        method.getReturnType().setCustomDataType(
                jTextFieldCustomReturn.getText());
        
        return method;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public final ElementListPanel getFieldsPanel() {
        return fieldsPanel;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneHeader = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanelPackageName = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jPanelProjectName1 = new javax.swing.JPanel();
        jLabelDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();
        jPanelFields = new javax.swing.JPanel();
        jPanelAccessibility = new javax.swing.JPanel();
        jLabelAccessibility = new javax.swing.JLabel();
        jComboBoxAccessibility = new javax.swing.JComboBox<>();
        jPanelKeyword = new javax.swing.JPanel();
        jLabelKeyword = new javax.swing.JLabel();
        jComboBoxKeyword = new javax.swing.JComboBox<>();
        jPanelPackageReturn = new javax.swing.JPanel();
        jLabelExtension = new javax.swing.JLabel();
        jComboBoxReturn = new javax.swing.JComboBox<>();
        jPanelPackageCustom = new javax.swing.JPanel();
        jLabelExtension1 = new javax.swing.JLabel();
        jTextFieldCustomReturn = new javax.swing.JTextField();
        jPanelError = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelErrorMessage = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jDesktopPaneHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD METHOD");
        jDesktopPaneHeader.add(jLabel1);

        add(jDesktopPaneHeader, java.awt.BorderLayout.NORTH);

        jPanelBody.setBorder(null);

        jLabelName.setLabelFor(jLabelName);
        jLabelName.setText("Name :");
        jLabelName.setToolTipText("");
        jLabelName.setPreferredSize(new java.awt.Dimension(238, 16));
        jPanelPackageName.add(jLabelName);

        jTextFieldName.setPreferredSize(new java.awt.Dimension(238, 28));
        jTextFieldName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldNameCaretUpdate(evt);
            }
        });
        jPanelPackageName.add(jTextFieldName);

        jPanelBody.add(jPanelPackageName);

        jLabelDesc.setLabelFor(jTextAreaDesc);
        jLabelDesc.setText("Description :");
        jLabelDesc.setPreferredSize(new java.awt.Dimension(238, 16));
        jPanelProjectName1.add(jLabelDesc);

        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDesc);

        jPanelProjectName1.add(jScrollPane1);

        jPanelBody.add(jPanelProjectName1);
        jPanelBody.add(jPanelFields);

        jLabelAccessibility.setText("Accessibility :");
        jLabelAccessibility.setPreferredSize(new java.awt.Dimension(238, 16));
        jPanelAccessibility.add(jLabelAccessibility);

        jComboBoxAccessibility.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAccessibility.setPreferredSize(new java.awt.Dimension(238, 26));
        jPanelAccessibility.add(jComboBoxAccessibility);

        jPanelBody.add(jPanelAccessibility);

        jLabelKeyword.setText("Keyword :");
        jLabelKeyword.setPreferredSize(new java.awt.Dimension(238, 16));
        jPanelKeyword.add(jLabelKeyword);

        jComboBoxKeyword.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxKeyword.setPreferredSize(new java.awt.Dimension(238, 26));
        jPanelKeyword.add(jComboBoxKeyword);

        jPanelBody.add(jPanelKeyword);

        jLabelExtension.setText("Return type :");
        jLabelExtension.setPreferredSize(new java.awt.Dimension(238, 16));
        jPanelPackageReturn.add(jLabelExtension);

        jComboBoxReturn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxReturn.setPreferredSize(new java.awt.Dimension(238, 26));
        jComboBoxReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReturnActionPerformed(evt);
            }
        });
        jPanelPackageReturn.add(jComboBoxReturn);

        jPanelBody.add(jPanelPackageReturn);

        jLabelExtension1.setText("Custom return type :");
        jLabelExtension1.setPreferredSize(new java.awt.Dimension(238, 16));
        jPanelPackageCustom.add(jLabelExtension1);

        jTextFieldCustomReturn.setPreferredSize(new java.awt.Dimension(238, 28));
        jPanelPackageCustom.add(jTextFieldCustomReturn);

        jPanelBody.add(jPanelPackageCustom);

        jPanelError.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        jPanelError.setPreferredSize(new java.awt.Dimension(478, 28));
        jPanelError.setRequestFocusEnabled(false);

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Error :");
        jPanelError.add(jLabel2);

        jLabelErrorMessage.setText("jLabel3");
        jPanelError.add(jLabelErrorMessage);

        jPanelBody.add(jPanelError);

        add(jPanelBody, java.awt.BorderLayout.CENTER);

        jPanelFooter.setBackground(new java.awt.Color(171, 181, 191));

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelFooter.add(jButtonCancel);

        jButtonAccept.setText("Accept");
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });
        jPanelFooter.add(jButtonAccept);

        add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final synchronized void setOnAcceptCallback(
            final Runnable onAcceptCallback) {
        this.onAcceptCallback = onAcceptCallback;
    }

    public final synchronized void setOnChangeNameCallback(
            final Consumer<String> onChangeNameCallback) {
        this.onChangeNameCallback = onChangeNameCallback;
    }
    
    public final String getFieldName() {
        return jTextFieldName.getText();
    }
    
    public final String getDescription() {
        return jTextAreaDesc.getText();
    }
    
    public final void setAvailableName(final boolean available) {
        this.validName = available;
        jPanelError.setVisible(!available);
        
        if (!available) {
            jLabelErrorMessage.setText("The name is not valid");
        }
    }
    
    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        if (jTextFieldName.getText() == null || jTextFieldName.getText().isEmpty()) {
            setAvailableName(false);
        }
        
        if (validName) {
            if (onAcceptCallback != null) {
                onAcceptCallback.run();
            }

            closeDialog(null);
        }
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    private void jTextFieldNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldNameCaretUpdate
        if (onChangeNameCallback != null) {
            onChangeNameCallback.accept(jTextFieldName.getText());
        }
    }//GEN-LAST:event_jTextFieldNameCaretUpdate

    private void jComboBoxReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReturnActionPerformed
        if (jComboBoxReturn.getSelectedItem() == JDataType.CUSTOM.getName()) {
            jTextFieldCustomReturn.setVisible(true);
        } else {
            jTextFieldCustomReturn.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddMethodDialog dialog = new AddMethodDialog(new java.awt.Frame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox<String> jComboBoxAccessibility;
    private javax.swing.JComboBox<String> jComboBoxKeyword;
    private javax.swing.JComboBox<String> jComboBoxReturn;
    private javax.swing.JDesktopPane jDesktopPaneHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAccessibility;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JLabel jLabelExtension;
    private javax.swing.JLabel jLabelExtension1;
    private javax.swing.JLabel jLabelKeyword;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanelAccessibility;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelError;
    private javax.swing.JPanel jPanelFields;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelKeyword;
    private javax.swing.JPanel jPanelPackageCustom;
    private javax.swing.JPanel jPanelPackageName;
    private javax.swing.JPanel jPanelPackageReturn;
    private javax.swing.JPanel jPanelProjectName1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDesc;
    private javax.swing.JTextField jTextFieldCustomReturn;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
