/*
 * Copyright (C) 2019 Tristan Muller
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package github.karakoukie.jumlcreator.views;

import org.apache.http.annotation.GuardedBy;

/**
 *
 * @author Tristan Muller
 */
public class CreateProjectDialog extends java.awt.Dialog {

    @GuardedBy("this")
    private Runnable onAcceptCallback;
    
    /**
     * Creates new form CreateProjectDialog
     * @param parent
     */
    public CreateProjectDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        this.onAcceptCallback = null;
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneHeader = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanelProjectName = new javax.swing.JPanel();
        jLabelProjectName = new javax.swing.JLabel();
        jTextFieldProjectName = new javax.swing.JTextField();
        jPanelProjectName1 = new javax.swing.JPanel();
        jLabelProjectName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();
        jPanelFooter = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();

        setModal(true);
        setPreferredSize(new java.awt.Dimension(602, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jDesktopPaneHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREATE PROJECT");
        jDesktopPaneHeader.add(jLabel1);

        add(jDesktopPaneHeader, java.awt.BorderLayout.NORTH);

        jPanelBody.setBorder(null);

        jLabelProjectName.setText("Name :");
        jLabelProjectName.setMinimumSize(new java.awt.Dimension(23, 16));
        jLabelProjectName.setPreferredSize(new java.awt.Dimension(238, 16));
        jPanelProjectName.add(jLabelProjectName);

        jTextFieldProjectName.setPreferredSize(new java.awt.Dimension(238, 28));
        jPanelProjectName.add(jTextFieldProjectName);

        jPanelBody.add(jPanelProjectName);

        jLabelProjectName1.setText("Description :");
        jLabelProjectName1.setPreferredSize(new java.awt.Dimension(238, 16));
        jPanelProjectName1.add(jLabelProjectName1);

        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDesc);

        jPanelProjectName1.add(jScrollPane1);

        jPanelBody.add(jPanelProjectName1);

        add(jPanelBody, java.awt.BorderLayout.CENTER);

        jPanelFooter.setBackground(new java.awt.Color(171, 181, 191));

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelFooter.add(jButtonCancel);

        jButtonAccept.setText("Accept");
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });
        jPanelFooter.add(jButtonAccept);

        add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final synchronized void setOnAcceptCallback(
            final Runnable onAcceptCallback) {
        this.onAcceptCallback = onAcceptCallback;
    }
    
    public final String getProjectName() {
        return jTextFieldProjectName.getText();
    }
    
    public final String getDescription() {
        return jTextAreaDesc.getText();
    }
    
    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        if (onAcceptCallback != null) {
            onAcceptCallback.run();
        }
        
        closeDialog(null);
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateProjectDialog dialog = new CreateProjectDialog(new java.awt.Frame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JDesktopPane jDesktopPaneHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelProjectName;
    private javax.swing.JLabel jLabelProjectName1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelProjectName;
    private javax.swing.JPanel jPanelProjectName1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDesc;
    private javax.swing.JTextField jTextFieldProjectName;
    // End of variables declaration//GEN-END:variables
}
