/*
 * Copyright (C) 2019 Tristan Muller (tristan.muller@cirad.fr)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package github.karakoukie.jumlcreator.views;

/**
 *
 * @author Tristan Muller (tristan.muller@cirad.fr)
 */
public class NewJPanel extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public NewJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelHeader.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelHeader.setLayout(new java.awt.CardLayout(10, 10));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("github/karakoukie/jumlcreator/views/Bundle"); // NOI18N
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("NewJPanel.jPanel5.border.title"))); // NOI18N
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 0, 0));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(bundle.getString("NewJPanel.jLabel1.text")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 15));
        jPanel5.add(jLabel1);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText(bundle.getString("NewJPanel.jLabel4.text")); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 15));
        jPanel5.add(jLabel4);

        jPanelHeader.add(jPanel5, "card2");

        add(jPanelHeader, java.awt.BorderLayout.WEST);

        jPanelBody.setLayout(new java.awt.CardLayout(10, 10));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("NewJPanel.jPanel3.border.title"))); // NOI18N

        jPanel7.setPreferredSize(new java.awt.Dimension(500, 27));
        jPanel7.setLayout(new java.awt.GridLayout(0, 1));

        jLabel5.setText(bundle.getString("NewJPanel.jLabel5.text")); // NOI18N
        jPanel7.add(jLabel5);

        jPanel3.add(jPanel7);

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 27));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText(bundle.getString("NewJPanel.jLabel2.text")); // NOI18N
        jPanel2.add(jLabel2);

        jTextField1.setText(bundle.getString("NewJPanel.jTextField1.text")); // NOI18N
        jPanel2.add(jTextField1);

        jPanel3.add(jPanel2);

        jPanel4.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText(bundle.getString("NewJPanel.jLabel3.text")); // NOI18N
        jLabel3.setPreferredSize(null);
        jPanel4.add(jLabel3);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@author", "@since" }));
        jPanel9.add(jComboBox1);

        jButton5.setText(bundle.getString("NewJPanel.jButton5.text")); // NOI18N
        jPanel9.add(jButton5);

        jPanel8.add(jPanel9, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel8);

        jPanel3.add(jPanel4);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 47));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dialog-error.png"))); // NOI18N
        jLabel6.setText(bundle.getString("NewJPanel.jLabel6.text")); // NOI18N
        jLabel6.setToolTipText(bundle.getString("NewJPanel.jLabel6.toolTipText")); // NOI18N
        jPanel1.add(jLabel6);

        jPanel3.add(jPanel1);

        jPanelBody.add(jPanel3, "card2");

        add(jPanelBody, java.awt.BorderLayout.CENTER);

        jPanelFooter.setLayout(new java.awt.CardLayout(10, 10));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel6.setLayout(flowLayout1);

        jButton2.setText(bundle.getString("NewJPanel.jButton2.text")); // NOI18N
        jPanel6.add(jButton2);

        jButton3.setText(bundle.getString("NewJPanel.jButton3.text")); // NOI18N
        jPanel6.add(jButton3);

        jButton4.setText(bundle.getString("NewJPanel.jButton4.text")); // NOI18N
        jPanel6.add(jButton4);

        jButton1.setText(bundle.getString("NewJPanel.jButton1.text")); // NOI18N
        jPanel6.add(jButton1);

        jPanelFooter.add(jPanel6, "card2");

        add(jPanelFooter, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
